from setuptools import setup, find_packages

setup(
    name="hinglishswd",
    version="0.1.2",
    description="A Python library for Hinglish (Hindi+English code-mixed) NLP: detection, tokenization, transliteration, stop-word removal.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Abhinav Patra",
    author_email="patraabhinav12@gmail.com",
    url="https://github.com/abhinavpatra/hinglishwd",
    project_urls={
        "Source": "https://github.com/abhinavpatra/hinglishwd",
        "Website": "https://abhinavpatra.tech",
    },
    license="Modified MIT License",
    packages=find_packages(),
    install_requires=[
        "indic-transliteration>=2.0.0",
    ],
    extras_require={
        "spacy": ["spacy>=3.0.0"],
        "translate": ["deep-translator>=1.0.0"],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: Other/Proprietary License",
        "Natural Language :: English",
        "Natural Language :: Hindi",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing",
        "Topic :: Text Processing :: Filters",
        "Topic :: Text Processing :: Linguistic",
    ],
)
